[project]
name = "ocr-api"
version = "0.1.0"
description = "OCR API for Flexbone"
readme = "README.md"
authors = [
    { name = "Rafidul Islam", email = "rafidul258@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "google-cloud-vision>=3.15.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "ruff>=0.16.3",
]

[project.scripts]
ocr-api = "ocr_api:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "ocr_api.main:app"

[tool.ruff]
target-version = "py314"
line-length = 110

[tool.ruff.lint]
select = ["E", "W", "F"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
]
